/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class DeleteOrgsOrgIdWorkloadProfilesProfileIdVersionsVersionRequest {
    /**
     * The Organization ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;
    public DeleteOrgsOrgIdWorkloadProfilesProfileIdVersionsVersionRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    /**
     * The Workload profile ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=profileId")
    public String profileId;
    public DeleteOrgsOrgIdWorkloadProfilesProfileIdVersionsVersionRequest withProfileId(String profileId) {
        this.profileId = profileId;
        return this;
    }
    
    /**
     * The Version.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=version")
    public String version;
    public DeleteOrgsOrgIdWorkloadProfilesProfileIdVersionsVersionRequest withVersion(String version) {
        this.version = version;
        return this;
    }
    
    public DeleteOrgsOrgIdWorkloadProfilesProfileIdVersionsVersionRequest(@JsonProperty("orgId") String orgId, @JsonProperty("profileId") String profileId, @JsonProperty("version") String version) {
        this.orgId = orgId;
        this.profileId = profileId;
        this.version = version;
  }
}
