/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class DeleteOrgsOrgIdUsersUserIdRequest {
    /**
     * The Organization ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;
    public DeleteOrgsOrgIdUsersUserIdRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    /**
     * The User ID
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=userId")
    public String userId;
    public DeleteOrgsOrgIdUsersUserIdRequest withUserId(String userId) {
        this.userId = userId;
        return this;
    }
    
    public DeleteOrgsOrgIdUsersUserIdRequest(@JsonProperty("orgId") String orgId, @JsonProperty("userId") String userId) {
        this.orgId = orgId;
        this.userId = userId;
  }
}
