/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class DeleteOrgsOrgIdResourcesDefsDefIdRequest {
    /**
     * The Resource Definition ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=defId")
    public String defId;

    public DeleteOrgsOrgIdResourcesDefsDefIdRequest withDefId(String defId) {
        this.defId = defId;
        return this;
    }
    
    /**
     * If set to `true`, will mark the Resource Definition for deletion, even if it affects existing Active Resources.
     * 
     * 
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=force")
    public Boolean force;

    public DeleteOrgsOrgIdResourcesDefsDefIdRequest withForce(Boolean force) {
        this.force = force;
        return this;
    }
    
    /**
     * The Organization ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;

    public DeleteOrgsOrgIdResourcesDefsDefIdRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    public DeleteOrgsOrgIdResourcesDefsDefIdRequest(@JsonProperty("defId") String defId, @JsonProperty("orgId") String orgId) {
        this.defId = defId;
        this.orgId = orgId;
  }
}
