/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class DeleteOrgsOrgIdAppsAppIdValuesKeyRequest {
    /**
     * The Application ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=appId")
    public String appId;
    public DeleteOrgsOrgIdAppsAppIdValuesKeyRequest withAppId(String appId) {
        this.appId = appId;
        return this;
    }
    
    /**
     * The key to update.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=key")
    public String key;
    public DeleteOrgsOrgIdAppsAppIdValuesKeyRequest withKey(String key) {
        this.key = key;
        return this;
    }
    
    /**
     * The Organization ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;
    public DeleteOrgsOrgIdAppsAppIdValuesKeyRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    public DeleteOrgsOrgIdAppsAppIdValuesKeyRequest(@JsonProperty("appId") String appId, @JsonProperty("key") String key, @JsonProperty("orgId") String orgId) {
        this.appId = appId;
        this.key = key;
        this.orgId = orgId;
  }
}
