/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class DeleteOrgsOrgIdArtefactsArtefactIdRequest {
    /**
     * The Artefact ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=artefactId")
    public String artefactId;
    public DeleteOrgsOrgIdArtefactsArtefactIdRequest withArtefactId(String artefactId) {
        this.artefactId = artefactId;
        return this;
    }
    
    /**
     * The organization ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;
    public DeleteOrgsOrgIdArtefactsArtefactIdRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    public DeleteOrgsOrgIdArtefactsArtefactIdRequest(@JsonProperty("artefactId") String artefactId, @JsonProperty("orgId") String orgId) {
        this.artefactId = artefactId;
        this.orgId = orgId;
  }
}
