/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class DeleteOrgsOrgIdWorkloadProfilesProfileIdVersionsVersionResponse {
    
    public String contentType;
    public DeleteOrgsOrgIdWorkloadProfilesProfileIdVersionsVersionResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * The Workload Profile Version is not found or is not accessible by the organization.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse;
    public DeleteOrgsOrgIdWorkloadProfilesProfileIdVersionsVersionResponse withHumanitecErrorResponse(demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse) {
        this.humanitecErrorResponse = humanitecErrorResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public DeleteOrgsOrgIdWorkloadProfilesProfileIdVersionsVersionResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public DeleteOrgsOrgIdWorkloadProfilesProfileIdVersionsVersionResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public DeleteOrgsOrgIdWorkloadProfilesProfileIdVersionsVersionResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
