/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class DeleteOrgsOrgIdResourcesDefsDefIdCriteriaCriteriaIdResponse {
    
    public String contentType;

    public DeleteOrgsOrgIdResourcesDefsDefIdCriteriaCriteriaIdResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Internal application error.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse;

    public DeleteOrgsOrgIdResourcesDefsDefIdCriteriaCriteriaIdResponse withHumanitecErrorResponse(demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse) {
        this.humanitecErrorResponse = humanitecErrorResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public DeleteOrgsOrgIdResourcesDefsDefIdCriteriaCriteriaIdResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public DeleteOrgsOrgIdResourcesDefsDefIdCriteriaCriteriaIdResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * One or more Active Resources reference the Resource Definition through this Matching Criteria.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.ResourceDefinitionChangeResponse[] resourceDefinitionChangeResponses;

    public DeleteOrgsOrgIdResourcesDefsDefIdCriteriaCriteriaIdResponse withResourceDefinitionChangeResponses(demo_1.test_1.models.shared.ResourceDefinitionChangeResponse[] resourceDefinitionChangeResponses) {
        this.resourceDefinitionChangeResponses = resourceDefinitionChangeResponses;
        return this;
    }
    
    /**
     * The Resource Definition is not found.
     * 
     * 
     */
    
    public String deleteOrgsOrgIdResourcesDefsDefIdCriteriaCriteriaId404ApplicationJSONString;

    public DeleteOrgsOrgIdResourcesDefsDefIdCriteriaCriteriaIdResponse withDeleteOrgsOrgIdResourcesDefsDefIdCriteriaCriteriaId404ApplicationJSONString(String deleteOrgsOrgIdResourcesDefsDefIdCriteriaCriteriaId404ApplicationJSONString) {
        this.deleteOrgsOrgIdResourcesDefsDefIdCriteriaCriteriaId404ApplicationJSONString = deleteOrgsOrgIdResourcesDefsDefIdCriteriaCriteriaId404ApplicationJSONString;
        return this;
    }
    
    public DeleteOrgsOrgIdResourcesDefsDefIdCriteriaCriteriaIdResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
