/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class DeleteOrgsOrgIdEnvTypesEnvTypeIdResponse {
    
    public String contentType;

    public DeleteOrgsOrgIdEnvTypesEnvTypeIdResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * The Environment Type requested.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.EnvironmentTypeResponse environmentTypeResponse;

    public DeleteOrgsOrgIdEnvTypesEnvTypeIdResponse withEnvironmentTypeResponse(demo_1.test_1.models.shared.EnvironmentTypeResponse environmentTypeResponse) {
        this.environmentTypeResponse = environmentTypeResponse;
        return this;
    }
    
    /**
     * The Authorization header was not present or invalid.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse;

    public DeleteOrgsOrgIdEnvTypesEnvTypeIdResponse withHumanitecErrorResponse(demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse) {
        this.humanitecErrorResponse = humanitecErrorResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public DeleteOrgsOrgIdEnvTypesEnvTypeIdResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public DeleteOrgsOrgIdEnvTypesEnvTypeIdResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * There are 1 or more Environments with this Type.
     * 
     * To delete an Environment Type, there can be no Environments with that type in the Organization.
     */
    
    public java.util.Map<String, String>[] deleteOrgsOrgIdEnvTypesEnvTypeId409ApplicationJSONObjects;

    public DeleteOrgsOrgIdEnvTypesEnvTypeIdResponse withDeleteOrgsOrgIdEnvTypesEnvTypeId409ApplicationJSONObjects(java.util.Map<String, String>[] deleteOrgsOrgIdEnvTypesEnvTypeId409ApplicationJSONObjects) {
        this.deleteOrgsOrgIdEnvTypesEnvTypeId409ApplicationJSONObjects = deleteOrgsOrgIdEnvTypesEnvTypeId409ApplicationJSONObjects;
        return this;
    }
    
    public DeleteOrgsOrgIdEnvTypesEnvTypeIdResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
