/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetCurrentUserResponse {
    
    public String contentType;

    public GetCurrentUserResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetCurrentUserResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetCurrentUserResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * The extended user profile of the user.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.UserProfileExtendedResponse userProfileExtendedResponse;

    public GetCurrentUserResponse withUserProfileExtendedResponse(demo_1.test_1.models.shared.UserProfileExtendedResponse userProfileExtendedResponse) {
        this.userProfileExtendedResponse = userProfileExtendedResponse;
        return this;
    }
    
    public GetCurrentUserResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
