/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetOrgsOrgIdArtefactVersionsResponse {
    /**
     * A list of Artefact Versions registered with your organization.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.ArtefactVersionResponse[] artefactVersionResponses;

    public GetOrgsOrgIdArtefactVersionsResponse withArtefactVersionResponses(demo_1.test_1.models.shared.ArtefactVersionResponse[] artefactVersionResponses) {
        this.artefactVersionResponses = artefactVersionResponses;
        return this;
    }
    
    
    public String contentType;

    public GetOrgsOrgIdArtefactVersionsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Bad request.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse;

    public GetOrgsOrgIdArtefactVersionsResponse withHumanitecErrorResponse(demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse) {
        this.humanitecErrorResponse = humanitecErrorResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public GetOrgsOrgIdArtefactVersionsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetOrgsOrgIdArtefactVersionsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetOrgsOrgIdArtefactVersionsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
