/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetOrgsOrgIdAppsResponse {
    /**
     * Possibly empty list of Applications.
     */
    
    public demo_1.test_1.models.shared.ApplicationResponse[] applicationResponses;
    public GetOrgsOrgIdAppsResponse withApplicationResponses(demo_1.test_1.models.shared.ApplicationResponse[] applicationResponses) {
        this.applicationResponses = applicationResponses;
        return this;
    }
    
    
    public String contentType;
    public GetOrgsOrgIdAppsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public GetOrgsOrgIdAppsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetOrgsOrgIdAppsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetOrgsOrgIdAppsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
