/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetOrgsOrgIdAppsAppIdEnvsEnvIdRuntimeResponse {
    
    public String contentType;
    public GetOrgsOrgIdAppsAppIdEnvsEnvIdRuntimeResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Runtime info returned.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.RuntimeInfoResponse runtimeInfoResponse;
    public GetOrgsOrgIdAppsAppIdEnvsEnvIdRuntimeResponse withRuntimeInfoResponse(demo_1.test_1.models.shared.RuntimeInfoResponse runtimeInfoResponse) {
        this.runtimeInfoResponse = runtimeInfoResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public GetOrgsOrgIdAppsAppIdEnvsEnvIdRuntimeResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetOrgsOrgIdAppsAppIdEnvsEnvIdRuntimeResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetOrgsOrgIdAppsAppIdEnvsEnvIdRuntimeResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
