/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetOrgsOrgIdWorkloadProfilesResponse {
    
    public String contentType;
    public GetOrgsOrgIdWorkloadProfilesResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public GetOrgsOrgIdWorkloadProfilesResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetOrgsOrgIdWorkloadProfilesResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * A possibly empty list of Workload Profiles.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.WorkloadProfileResponse[] workloadProfileResponses;
    public GetOrgsOrgIdWorkloadProfilesResponse withWorkloadProfileResponses(demo_1.test_1.models.shared.WorkloadProfileResponse[] workloadProfileResponses) {
        this.workloadProfileResponses = workloadProfileResponses;
        return this;
    }
    
    public GetOrgsOrgIdWorkloadProfilesResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
