/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetOrgsOrgIdAppsAppIdUsersResponse {
    
    public String contentType;
    public GetOrgsOrgIdAppsAppIdUsersResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public GetOrgsOrgIdAppsAppIdUsersResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetOrgsOrgIdAppsAppIdUsersResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * A list of Users and the roles they hold.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.UserRoleResponse[] userRoleResponses;
    public GetOrgsOrgIdAppsAppIdUsersResponse withUserRoleResponses(demo_1.test_1.models.shared.UserRoleResponse[] userRoleResponses) {
        this.userRoleResponses = userRoleResponses;
        return this;
    }
    
    public GetOrgsOrgIdAppsAppIdUsersResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
