/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetOrgsOrgIdWorkloadProfilesProfileQidVersionsResponse {
    
    public String contentType;

    public GetOrgsOrgIdWorkloadProfilesProfileQidVersionsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Workload Profile Versions not found or not accessible by the organization.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse;

    public GetOrgsOrgIdWorkloadProfilesProfileQidVersionsResponse withHumanitecErrorResponse(demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse) {
        this.humanitecErrorResponse = humanitecErrorResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public GetOrgsOrgIdWorkloadProfilesProfileQidVersionsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetOrgsOrgIdWorkloadProfilesProfileQidVersionsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * A possibly empty list of Workload Profile Versions.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.WorkloadProfileVersionResponse[] workloadProfileVersionResponses;

    public GetOrgsOrgIdWorkloadProfilesProfileQidVersionsResponse withWorkloadProfileVersionResponses(demo_1.test_1.models.shared.WorkloadProfileVersionResponse[] workloadProfileVersionResponses) {
        this.workloadProfileVersionResponses = workloadProfileVersionResponses;
        return this;
    }
    
    public GetOrgsOrgIdWorkloadProfilesProfileQidVersionsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
