/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetOrgsOrgIdAppsAppIdSetsSetIdDiffSourceSetIdResponse {
    
    public String contentType;
    public GetOrgsOrgIdAppsAppIdSetsSetIdDiffSourceSetIdResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * A Deployment Delta which if applied to the Set with ID `sourceSetId` gives the Set with ID `setId`.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.PlainDeltaResponse plainDeltaResponse;
    public GetOrgsOrgIdAppsAppIdSetsSetIdDiffSourceSetIdResponse withPlainDeltaResponse(demo_1.test_1.models.shared.PlainDeltaResponse plainDeltaResponse) {
        this.plainDeltaResponse = plainDeltaResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public GetOrgsOrgIdAppsAppIdSetsSetIdDiffSourceSetIdResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetOrgsOrgIdAppsAppIdSetsSetIdDiffSourceSetIdResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * No Deployment Set with ID `setId` or `sourceSetId` found in Application.
     * 
     * 
     */
    
    public String getOrgsOrgIdAppsAppIdSetsSetIdDiffSourceSetId404ApplicationJSONString;
    public GetOrgsOrgIdAppsAppIdSetsSetIdDiffSourceSetIdResponse withGetOrgsOrgIdAppsAppIdSetsSetIdDiffSourceSetId404ApplicationJSONString(String getOrgsOrgIdAppsAppIdSetsSetIdDiffSourceSetId404ApplicationJSONString) {
        this.getOrgsOrgIdAppsAppIdSetsSetIdDiffSourceSetId404ApplicationJSONString = getOrgsOrgIdAppsAppIdSetsSetIdDiffSourceSetId404ApplicationJSONString;
        return this;
    }
    
    public GetOrgsOrgIdAppsAppIdSetsSetIdDiffSourceSetIdResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
