/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class GetOrgsOrgIdAppsAppIdEnvsEnvIdRulesRuleIdRequest {
    /**
     * The Application ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=appId")
    public String appId;
    public GetOrgsOrgIdAppsAppIdEnvsEnvIdRulesRuleIdRequest withAppId(String appId) {
        this.appId = appId;
        return this;
    }
    
    /**
     * The Environment ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=envId")
    public String envId;
    public GetOrgsOrgIdAppsAppIdEnvsEnvIdRulesRuleIdRequest withEnvId(String envId) {
        this.envId = envId;
        return this;
    }
    
    /**
     * The Organization ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;
    public GetOrgsOrgIdAppsAppIdEnvsEnvIdRulesRuleIdRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    /**
     * The Automation Rule ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=ruleId")
    public String ruleId;
    public GetOrgsOrgIdAppsAppIdEnvsEnvIdRulesRuleIdRequest withRuleId(String ruleId) {
        this.ruleId = ruleId;
        return this;
    }
    
    public GetOrgsOrgIdAppsAppIdEnvsEnvIdRulesRuleIdRequest(@JsonProperty("appId") String appId, @JsonProperty("envId") String envId, @JsonProperty("orgId") String orgId, @JsonProperty("ruleId") String ruleId) {
        this.appId = appId;
        this.envId = envId;
        this.orgId = orgId;
        this.ruleId = ruleId;
  }
}
