/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class GetOrgsOrgIdAppsAppIdDeltasRequest {
    /**
     * The Application ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=appId")
    public String appId;

    public GetOrgsOrgIdAppsAppIdDeltasRequest withAppId(String appId) {
        this.appId = appId;
        return this;
    }
    
    /**
     * If true, return archived Deltas.
     * 
     * 
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=archived")
    public Boolean archived;

    public GetOrgsOrgIdAppsAppIdDeltasRequest withArchived(Boolean archived) {
        this.archived = archived;
        return this;
    }
    
    /**
     * Only return Deltas associated with the specified Environment.
     * 
     * 
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=env")
    public String env;

    public GetOrgsOrgIdAppsAppIdDeltasRequest withEnv(String env) {
        this.env = env;
        return this;
    }
    
    /**
     * The Organization ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;

    public GetOrgsOrgIdAppsAppIdDeltasRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    public GetOrgsOrgIdAppsAppIdDeltasRequest(@JsonProperty("appId") String appId, @JsonProperty("orgId") String orgId) {
        this.appId = appId;
        this.orgId = orgId;
  }
}
