/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class GetOrgsOrgIdWorkloadProfilesProfileQidRequest {
    /**
     * The Organization ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;
    public GetOrgsOrgIdWorkloadProfilesProfileQidRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    /**
     * The fully qualified Workload ID. (If not a profile from the current org, must be prefixed with `{orgId}.` e.g. `humanitec.default-cronjob`)
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=profileQid")
    public String profileQid;
    public GetOrgsOrgIdWorkloadProfilesProfileQidRequest withProfileQid(String profileQid) {
        this.profileQid = profileQid;
        return this;
    }
    
    public GetOrgsOrgIdWorkloadProfilesProfileQidRequest(@JsonProperty("orgId") String orgId, @JsonProperty("profileQid") String profileQid) {
        this.orgId = orgId;
        this.profileQid = profileQid;
  }
}
