/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetOrgsOrgIdAppsAppIdEnvsEnvIdDeploysDeployIdErrorsResponse {
    
    public String contentType;
    public GetOrgsOrgIdAppsAppIdEnvsEnvIdDeploysDeployIdErrorsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * A List of deployment errors, could be empty.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.DeploymentErrorResponse[] deploymentErrorResponses;
    public GetOrgsOrgIdAppsAppIdEnvsEnvIdDeploysDeployIdErrorsResponse withDeploymentErrorResponses(demo_1.test_1.models.shared.DeploymentErrorResponse[] deploymentErrorResponses) {
        this.deploymentErrorResponses = deploymentErrorResponses;
        return this;
    }
    
    
    public Integer statusCode;
    public GetOrgsOrgIdAppsAppIdEnvsEnvIdDeploysDeployIdErrorsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetOrgsOrgIdAppsAppIdEnvsEnvIdDeploysDeployIdErrorsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetOrgsOrgIdAppsAppIdEnvsEnvIdDeploysDeployIdErrorsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
