/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetOrgsOrgIdAppsAppIdSetsSetIdResponse {
    
    public String contentType;
    public GetOrgsOrgIdAppsAppIdSetsSetIdResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public GetOrgsOrgIdAppsAppIdSetsSetIdResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetOrgsOrgIdAppsAppIdSetsSetIdResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * The Requested Deployment Set.
     * 
     * 
     */
    
    public Object getOrgsOrgIdAppsAppIdSetsSetId200ApplicationJSONOneOf;
    public GetOrgsOrgIdAppsAppIdSetsSetIdResponse withGetOrgsOrgIdAppsAppIdSetsSetId200ApplicationJSONOneOf(Object getOrgsOrgIdAppsAppIdSetsSetId200ApplicationJSONOneOf) {
        this.getOrgsOrgIdAppsAppIdSetsSetId200ApplicationJSONOneOf = getOrgsOrgIdAppsAppIdSetsSetId200ApplicationJSONOneOf;
        return this;
    }
    
    /**
     * No Deployment Set with ID `setId` found in Application.
     * 
     * 
     */
    
    public String getOrgsOrgIdAppsAppIdSetsSetId404ApplicationJSONString;
    public GetOrgsOrgIdAppsAppIdSetsSetIdResponse withGetOrgsOrgIdAppsAppIdSetsSetId404ApplicationJSONString(String getOrgsOrgIdAppsAppIdSetsSetId404ApplicationJSONString) {
        this.getOrgsOrgIdAppsAppIdSetsSetId404ApplicationJSONString = getOrgsOrgIdAppsAppIdSetsSetId404ApplicationJSONString;
        return this;
    }
    
    public GetOrgsOrgIdAppsAppIdSetsSetIdResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
