/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetOrgsOrgIdResourcesTypesResponse {
    
    public String contentType;
    public GetOrgsOrgIdResourcesTypesResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Internal application error.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse;
    public GetOrgsOrgIdResourcesTypesResponse withHumanitecErrorResponse(demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse) {
        this.humanitecErrorResponse = humanitecErrorResponse;
        return this;
    }
    
    /**
     * A possibly empty list of Resources Types.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.ResourceTypeResponse[] resourceTypeResponses;
    public GetOrgsOrgIdResourcesTypesResponse withResourceTypeResponses(demo_1.test_1.models.shared.ResourceTypeResponse[] resourceTypeResponses) {
        this.resourceTypeResponses = resourceTypeResponses;
        return this;
    }
    
    
    public Integer statusCode;
    public GetOrgsOrgIdResourcesTypesResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetOrgsOrgIdResourcesTypesResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetOrgsOrgIdResourcesTypesResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
