/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetOrgsOrgIdAppsAppIdEnvsResponse {
    
    public String contentType;

    public GetOrgsOrgIdAppsAppIdEnvsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * A list of Environments associated with an Application.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.EnvironmentResponse[] environmentResponses;

    public GetOrgsOrgIdAppsAppIdEnvsResponse withEnvironmentResponses(demo_1.test_1.models.shared.EnvironmentResponse[] environmentResponses) {
        this.environmentResponses = environmentResponses;
        return this;
    }
    
    
    public Integer statusCode;

    public GetOrgsOrgIdAppsAppIdEnvsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetOrgsOrgIdAppsAppIdEnvsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetOrgsOrgIdAppsAppIdEnvsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
