/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetOrgsOrgIdResourcesDriversDriverIdResponse {
    
    public String contentType;
    public GetOrgsOrgIdResourcesDriversDriverIdResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * The requested Resources Driver details.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.DriverDefinitionResponse driverDefinitionResponse;
    public GetOrgsOrgIdResourcesDriversDriverIdResponse withDriverDefinitionResponse(demo_1.test_1.models.shared.DriverDefinitionResponse driverDefinitionResponse) {
        this.driverDefinitionResponse = driverDefinitionResponse;
        return this;
    }
    
    /**
     * A Resource Driver with the 'driverId' ID is not found or is not accessible by the organization.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse;
    public GetOrgsOrgIdResourcesDriversDriverIdResponse withHumanitecErrorResponse(demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse) {
        this.humanitecErrorResponse = humanitecErrorResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public GetOrgsOrgIdResourcesDriversDriverIdResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetOrgsOrgIdResourcesDriversDriverIdResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetOrgsOrgIdResourcesDriversDriverIdResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
