/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetOrgsOrgIdArtefactsResponse {
    /**
     * The list of Artefacts within the organization.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.ArtefactResponse[] artefactResponses;

    public GetOrgsOrgIdArtefactsResponse withArtefactResponses(demo_1.test_1.models.shared.ArtefactResponse[] artefactResponses) {
        this.artefactResponses = artefactResponses;
        return this;
    }
    
    
    public String contentType;

    public GetOrgsOrgIdArtefactsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetOrgsOrgIdArtefactsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetOrgsOrgIdArtefactsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetOrgsOrgIdArtefactsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
