/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetOrgsOrgIdWorkloadProfilesProfileQidResponse {
    
    public String contentType;
    public GetOrgsOrgIdWorkloadProfilesProfileQidResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * The requested WorkloadProfile is not found.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse;
    public GetOrgsOrgIdWorkloadProfilesProfileQidResponse withHumanitecErrorResponse(demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse) {
        this.humanitecErrorResponse = humanitecErrorResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public GetOrgsOrgIdWorkloadProfilesProfileQidResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetOrgsOrgIdWorkloadProfilesProfileQidResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * The requested WorkloadProfile.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.WorkloadProfileResponse workloadProfileResponse;
    public GetOrgsOrgIdWorkloadProfilesProfileQidResponse withWorkloadProfileResponse(demo_1.test_1.models.shared.WorkloadProfileResponse workloadProfileResponse) {
        this.workloadProfileResponse = workloadProfileResponse;
        return this;
    }
    
    public GetOrgsOrgIdWorkloadProfilesProfileQidResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
