/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class GetOrgsOrgIdArtefactsArtefactIdVersionsRequest {
    /**
     * (Optional) Filter for non-archived Artefact Versions. If no filter is defined only non-archived Artefact Versions are returned, if the filter is true both archived and non-archived Versions are returned.
     * 
     * 
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=archived")
    public String archived;

    public GetOrgsOrgIdArtefactsArtefactIdVersionsRequest withArchived(String archived) {
        this.archived = archived;
        return this;
    }
    
    /**
     * The Artefact ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=artefactId")
    public String artefactId;

    public GetOrgsOrgIdArtefactsArtefactIdVersionsRequest withArtefactId(String artefactId) {
        this.artefactId = artefactId;
        return this;
    }
    
    /**
     * (Optional) Limit the number of versions returned by the endpoint.
     * 
     * 
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")
    public String limit;

    public GetOrgsOrgIdArtefactsArtefactIdVersionsRequest withLimit(String limit) {
        this.limit = limit;
        return this;
    }
    
    /**
     * The organization ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;

    public GetOrgsOrgIdArtefactsArtefactIdVersionsRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    /**
     * (Optional) Filter Artefact Versions by by name including a version or digest.
     * 
     * 
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=reference")
    public String reference;

    public GetOrgsOrgIdArtefactsArtefactIdVersionsRequest withReference(String reference) {
        this.reference = reference;
        return this;
    }
    
    public GetOrgsOrgIdArtefactsArtefactIdVersionsRequest(@JsonProperty("artefactId") String artefactId, @JsonProperty("orgId") String orgId) {
        this.artefactId = artefactId;
        this.orgId = orgId;
  }
}
