/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class GetOrgsOrgIdResourcesDefsRequest {
    /**
     * (Optional) Filter Resource Definitions that may match a specific Application.
     * 
     * 
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=app")
    public String app;

    public GetOrgsOrgIdResourcesDefsRequest withApp(String app) {
        this.app = app;
        return this;
    }
    
    /**
     * (Optional) Filter Resource Definitions that may match a specific Environment.
     * 
     * 
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=env")
    public String env;

    public GetOrgsOrgIdResourcesDefsRequest withEnv(String env) {
        this.env = env;
        return this;
    }
    
    /**
     * (Optional) Filter Resource Definitions that may match a specific Environment Type.
     * 
     * 
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=env_type")
    public String envType;

    public GetOrgsOrgIdResourcesDefsRequest withEnvType(String envType) {
        this.envType = envType;
        return this;
    }
    
    /**
     * The Organization ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;

    public GetOrgsOrgIdResourcesDefsRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    /**
     * (Optional) Filter Resource Definitions that may match a specific Resource.
     * 
     * 
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=res")
    public String res;

    public GetOrgsOrgIdResourcesDefsRequest withRes(String res) {
        this.res = res;
        return this;
    }
    
    /**
     * (Optional) Filter Resource Definitions that may match a specific Resource Type.
     * 
     * 
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=res_type")
    public String resType;

    public GetOrgsOrgIdResourcesDefsRequest withResType(String resType) {
        this.resType = resType;
        return this;
    }
    
    public GetOrgsOrgIdResourcesDefsRequest(@JsonProperty("orgId") String orgId) {
        this.orgId = orgId;
  }
}
