/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetOrgsOrgIdAppsAppIdValueSetVersionsValueSetVersionIdResponse {
    
    public String contentType;

    public GetOrgsOrgIdAppsAppIdValueSetVersionsValueSetVersionIdResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * ValueSetVersion with `valueSetVersionId` in App.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse;

    public GetOrgsOrgIdAppsAppIdValueSetVersionsValueSetVersionIdResponse withHumanitecErrorResponse(demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse) {
        this.humanitecErrorResponse = humanitecErrorResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public GetOrgsOrgIdAppsAppIdValueSetVersionsValueSetVersionIdResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetOrgsOrgIdAppsAppIdValueSetVersionsValueSetVersionIdResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * The requested ValueSetVersion
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.ValueSetVersionResponse valueSetVersionResponse;

    public GetOrgsOrgIdAppsAppIdValueSetVersionsValueSetVersionIdResponse withValueSetVersionResponse(demo_1.test_1.models.shared.ValueSetVersionResponse valueSetVersionResponse) {
        this.valueSetVersionResponse = valueSetVersionResponse;
        return this;
    }
    
    public GetOrgsOrgIdAppsAppIdValueSetVersionsValueSetVersionIdResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
