/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class GetOrgsOrgIdRegistriesRegIdRequest {
    /**
     * Unique (alpha-numerical) organization identifier.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;

    public GetOrgsOrgIdRegistriesRegIdRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    /**
     * Unique (alpha-numerical) registry identifier.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=regId")
    public String regId;

    public GetOrgsOrgIdRegistriesRegIdRequest withRegId(String regId) {
        this.regId = regId;
        return this;
    }
    
    public GetOrgsOrgIdRegistriesRegIdRequest(@JsonProperty("orgId") String orgId, @JsonProperty("regId") String regId) {
        this.orgId = orgId;
        this.regId = regId;
  }
}
