/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetOrgsOrgIdRegistriesRegIdResponse {
    
    public String contentType;
    public GetOrgsOrgIdRegistriesRegIdResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Request parameters are incomplete or invalid.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.ErrorInfoResponse errorInfoResponse;
    public GetOrgsOrgIdRegistriesRegIdResponse withErrorInfoResponse(demo_1.test_1.models.shared.ErrorInfoResponse errorInfoResponse) {
        this.errorInfoResponse = errorInfoResponse;
        return this;
    }
    
    /**
     * A registry details.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.RegistryResponse registryResponse;
    public GetOrgsOrgIdRegistriesRegIdResponse withRegistryResponse(demo_1.test_1.models.shared.RegistryResponse registryResponse) {
        this.registryResponse = registryResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public GetOrgsOrgIdRegistriesRegIdResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetOrgsOrgIdRegistriesRegIdResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetOrgsOrgIdRegistriesRegIdResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
