/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetOrgsOrgIdAppsAppIdEnvsEnvIdRulesResponse {
    /**
     * A possibly empty array of Automation Rules
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.AutomationRuleResponse[] automationRuleResponses;
    public GetOrgsOrgIdAppsAppIdEnvsEnvIdRulesResponse withAutomationRuleResponses(demo_1.test_1.models.shared.AutomationRuleResponse[] automationRuleResponses) {
        this.automationRuleResponses = automationRuleResponses;
        return this;
    }
    
    
    public String contentType;
    public GetOrgsOrgIdAppsAppIdEnvsEnvIdRulesResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public GetOrgsOrgIdAppsAppIdEnvsEnvIdRulesResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetOrgsOrgIdAppsAppIdEnvsEnvIdRulesResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetOrgsOrgIdAppsAppIdEnvsEnvIdRulesResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
