/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetTokensResponse {
    
    public String contentType;
    public GetTokensResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public GetTokensResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetTokensResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * The token structure.
     * 
     * 
     */
    
    public java.util.Map<String, Object> getTokens200ApplicationJSONObject;
    public GetTokensResponse withGetTokens200ApplicationJSONObject(java.util.Map<String, Object> getTokens200ApplicationJSONObject) {
        this.getTokens200ApplicationJSONObject = getTokens200ApplicationJSONObject;
        return this;
    }
    
    public GetTokensResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
