/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetUsersMeResponse {
    
    public String contentType;

    public GetUsersMeResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetUsersMeResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetUsersMeResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * The extended user profile of the user.
     * 
     * 
     */
    
    public java.util.Map<String, Object> getUsersMe200ApplicationJSONObject;

    public GetUsersMeResponse withGetUsersMe200ApplicationJSONObject(java.util.Map<String, Object> getUsersMe200ApplicationJSONObject) {
        this.getUsersMe200ApplicationJSONObject = getUsersMe200ApplicationJSONObject;
        return this;
    }
    
    public GetUsersMeResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
