/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class PatchOrgsOrgIdAppsAppIdEnvsEnvIdValuesKeyResponse {
    
    public String contentType;
    public PatchOrgsOrgIdAppsAppIdEnvsEnvIdValuesKeyResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Input not valid.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse;
    public PatchOrgsOrgIdAppsAppIdEnvsEnvIdValuesKeyResponse withHumanitecErrorResponse(demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse) {
        this.humanitecErrorResponse = humanitecErrorResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public PatchOrgsOrgIdAppsAppIdEnvsEnvIdValuesKeyResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public PatchOrgsOrgIdAppsAppIdEnvsEnvIdValuesKeyResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Shared Value successfully updated.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.ValueResponse valueResponse;
    public PatchOrgsOrgIdAppsAppIdEnvsEnvIdValuesKeyResponse withValueResponse(demo_1.test_1.models.shared.ValueResponse valueResponse) {
        this.valueResponse = valueResponse;
        return this;
    }
    
    public PatchOrgsOrgIdAppsAppIdEnvsEnvIdValuesKeyResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
