/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class PatchOrgsOrgIdArtefactsArtefactIdVersionsVersionIdRequest {
    /**
     * The Artefact Version Update Request. Only the field `archive` can be updated.
     * 
     * 
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    public demo_1.test_1.models.shared.UpdateArtefactVersionPayloadRequest updateArtefactVersionPayloadRequest;
    public PatchOrgsOrgIdArtefactsArtefactIdVersionsVersionIdRequest withUpdateArtefactVersionPayloadRequest(demo_1.test_1.models.shared.UpdateArtefactVersionPayloadRequest updateArtefactVersionPayloadRequest) {
        this.updateArtefactVersionPayloadRequest = updateArtefactVersionPayloadRequest;
        return this;
    }
    
    /**
     * The Artefact ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=artefactId")
    public String artefactId;
    public PatchOrgsOrgIdArtefactsArtefactIdVersionsVersionIdRequest withArtefactId(String artefactId) {
        this.artefactId = artefactId;
        return this;
    }
    
    /**
     * The organization ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;
    public PatchOrgsOrgIdArtefactsArtefactIdVersionsVersionIdRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    /**
     * The Version ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=versionId")
    public String versionId;
    public PatchOrgsOrgIdArtefactsArtefactIdVersionsVersionIdRequest withVersionId(String versionId) {
        this.versionId = versionId;
        return this;
    }
    
    public PatchOrgsOrgIdArtefactsArtefactIdVersionsVersionIdRequest(@JsonProperty("UpdateArtefactVersionPayloadRequest") demo_1.test_1.models.shared.UpdateArtefactVersionPayloadRequest updateArtefactVersionPayloadRequest, @JsonProperty("artefactId") String artefactId, @JsonProperty("orgId") String orgId, @JsonProperty("versionId") String versionId) {
        this.updateArtefactVersionPayloadRequest = updateArtefactVersionPayloadRequest;
        this.artefactId = artefactId;
        this.orgId = orgId;
        this.versionId = versionId;
  }
}
