/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class PatchOrgsOrgIdAppsAppIdUsersUserIdRequest {
    /**
     * The new user role
     * 
     * 
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    public demo_1.test_1.models.shared.RoleRequest roleRequest;
    public PatchOrgsOrgIdAppsAppIdUsersUserIdRequest withRoleRequest(demo_1.test_1.models.shared.RoleRequest roleRequest) {
        this.roleRequest = roleRequest;
        return this;
    }
    
    /**
     * The Application ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=appId")
    public String appId;
    public PatchOrgsOrgIdAppsAppIdUsersUserIdRequest withAppId(String appId) {
        this.appId = appId;
        return this;
    }
    
    /**
     * The Organization ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;
    public PatchOrgsOrgIdAppsAppIdUsersUserIdRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    /**
     * The User ID
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=userId")
    public String userId;
    public PatchOrgsOrgIdAppsAppIdUsersUserIdRequest withUserId(String userId) {
        this.userId = userId;
        return this;
    }
    
    public PatchOrgsOrgIdAppsAppIdUsersUserIdRequest(@JsonProperty("RoleRequest") demo_1.test_1.models.shared.RoleRequest roleRequest, @JsonProperty("appId") String appId, @JsonProperty("orgId") String orgId, @JsonProperty("userId") String userId) {
        this.roleRequest = roleRequest;
        this.appId = appId;
        this.orgId = orgId;
        this.userId = userId;
  }
}
