/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class PatchOrgsOrgIdResourcesAccountsAccIdResponse {
    
    public String contentType;
    public PatchOrgsOrgIdResourcesAccountsAccIdResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * One or more request parameters is missing or invalid.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse;
    public PatchOrgsOrgIdResourcesAccountsAccIdResponse withHumanitecErrorResponse(demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse) {
        this.humanitecErrorResponse = humanitecErrorResponse;
        return this;
    }
    
    /**
     * The updated Resource Account details.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.ResourceAccountResponse resourceAccountResponse;
    public PatchOrgsOrgIdResourcesAccountsAccIdResponse withResourceAccountResponse(demo_1.test_1.models.shared.ResourceAccountResponse resourceAccountResponse) {
        this.resourceAccountResponse = resourceAccountResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public PatchOrgsOrgIdResourcesAccountsAccIdResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public PatchOrgsOrgIdResourcesAccountsAccIdResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public PatchOrgsOrgIdResourcesAccountsAccIdResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
