/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class PatchOrgsOrgIdEnvTypesEnvTypeUsersUserIdRequest {
    /**
     * The new user role
     * 
     * 
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    public demo_1.test_1.models.shared.RoleRequest roleRequest;
    public PatchOrgsOrgIdEnvTypesEnvTypeUsersUserIdRequest withRoleRequest(demo_1.test_1.models.shared.RoleRequest roleRequest) {
        this.roleRequest = roleRequest;
        return this;
    }
    
    /**
     * The Environment Type.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=envType")
    public String envType;
    public PatchOrgsOrgIdEnvTypesEnvTypeUsersUserIdRequest withEnvType(String envType) {
        this.envType = envType;
        return this;
    }
    
    /**
     * The Organization ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;
    public PatchOrgsOrgIdEnvTypesEnvTypeUsersUserIdRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    /**
     * The User ID
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=userId")
    public String userId;
    public PatchOrgsOrgIdEnvTypesEnvTypeUsersUserIdRequest withUserId(String userId) {
        this.userId = userId;
        return this;
    }
    
    public PatchOrgsOrgIdEnvTypesEnvTypeUsersUserIdRequest(@JsonProperty("RoleRequest") demo_1.test_1.models.shared.RoleRequest roleRequest, @JsonProperty("envType") String envType, @JsonProperty("orgId") String orgId, @JsonProperty("userId") String userId) {
        this.roleRequest = roleRequest;
        this.envType = envType;
        this.orgId = orgId;
        this.userId = userId;
  }
}
