/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class PatchOrgsOrgIdAppsAppIdValuesKeyRequest {
    /**
     * At least `value` or `description` must be supplied. All other fields will be ignored.
     * 
     * 
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    public demo_1.test_1.models.shared.ValuePatchPayloadRequest valuePatchPayloadRequest;
    public PatchOrgsOrgIdAppsAppIdValuesKeyRequest withValuePatchPayloadRequest(demo_1.test_1.models.shared.ValuePatchPayloadRequest valuePatchPayloadRequest) {
        this.valuePatchPayloadRequest = valuePatchPayloadRequest;
        return this;
    }
    
    /**
     * The Application ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=appId")
    public String appId;
    public PatchOrgsOrgIdAppsAppIdValuesKeyRequest withAppId(String appId) {
        this.appId = appId;
        return this;
    }
    
    /**
     * The key to update.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=key")
    public String key;
    public PatchOrgsOrgIdAppsAppIdValuesKeyRequest withKey(String key) {
        this.key = key;
        return this;
    }
    
    /**
     * The Organization ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;
    public PatchOrgsOrgIdAppsAppIdValuesKeyRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    public PatchOrgsOrgIdAppsAppIdValuesKeyRequest(@JsonProperty("ValuePatchPayloadRequest") demo_1.test_1.models.shared.ValuePatchPayloadRequest valuePatchPayloadRequest, @JsonProperty("appId") String appId, @JsonProperty("key") String key, @JsonProperty("orgId") String orgId) {
        this.valuePatchPayloadRequest = valuePatchPayloadRequest;
        this.appId = appId;
        this.key = key;
        this.orgId = orgId;
  }
}
