/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class PatchCurrentUserResponse {
    
    public String contentType;
    public PatchCurrentUserResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * The request was invalid or the payload malformed.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse;
    public PatchCurrentUserResponse withHumanitecErrorResponse(demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse) {
        this.humanitecErrorResponse = humanitecErrorResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public PatchCurrentUserResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public PatchCurrentUserResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * The extended user profile of the user.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.UserProfileExtendedResponse userProfileExtendedResponse;
    public PatchCurrentUserResponse withUserProfileExtendedResponse(demo_1.test_1.models.shared.UserProfileExtendedResponse userProfileExtendedResponse) {
        this.userProfileExtendedResponse = userProfileExtendedResponse;
        return this;
    }
    
    public PatchCurrentUserResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
