/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class PostOrgsOrgIdResourcesDriversRequest {
    /**
     * Resources Driver details.
     * 
     * 
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    public demo_1.test_1.models.shared.CreateDriverRequestRequest createDriverRequestRequest;

    public PostOrgsOrgIdResourcesDriversRequest withCreateDriverRequestRequest(demo_1.test_1.models.shared.CreateDriverRequestRequest createDriverRequestRequest) {
        this.createDriverRequestRequest = createDriverRequestRequest;
        return this;
    }
    
    /**
     * The Organization ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;

    public PostOrgsOrgIdResourcesDriversRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    public PostOrgsOrgIdResourcesDriversRequest(@JsonProperty("CreateDriverRequestRequest") demo_1.test_1.models.shared.CreateDriverRequestRequest createDriverRequestRequest, @JsonProperty("orgId") String orgId) {
        this.createDriverRequestRequest = createDriverRequestRequest;
        this.orgId = orgId;
  }
}
