/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class PostOrgsOrgIdAppsAppIdEnvsEnvIdRulesRequest {
    /**
     * The definition of the Automation Rule.
     * 
     * 
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    public demo_1.test_1.models.shared.AutomationRuleRequest automationRuleRequest;
    public PostOrgsOrgIdAppsAppIdEnvsEnvIdRulesRequest withAutomationRuleRequest(demo_1.test_1.models.shared.AutomationRuleRequest automationRuleRequest) {
        this.automationRuleRequest = automationRuleRequest;
        return this;
    }
    
    /**
     * The Application ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=appId")
    public String appId;
    public PostOrgsOrgIdAppsAppIdEnvsEnvIdRulesRequest withAppId(String appId) {
        this.appId = appId;
        return this;
    }
    
    /**
     * The Environment ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=envId")
    public String envId;
    public PostOrgsOrgIdAppsAppIdEnvsEnvIdRulesRequest withEnvId(String envId) {
        this.envId = envId;
        return this;
    }
    
    /**
     * The Organization ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;
    public PostOrgsOrgIdAppsAppIdEnvsEnvIdRulesRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    public PostOrgsOrgIdAppsAppIdEnvsEnvIdRulesRequest(@JsonProperty("AutomationRuleRequest") demo_1.test_1.models.shared.AutomationRuleRequest automationRuleRequest, @JsonProperty("appId") String appId, @JsonProperty("envId") String envId, @JsonProperty("orgId") String orgId) {
        this.automationRuleRequest = automationRuleRequest;
        this.appId = appId;
        this.envId = envId;
        this.orgId = orgId;
  }
}
