/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class PostOrgsOrgIdAppsAppIdEnvsEnvIdRulesResponse {
    /**
     * The AutomationRule
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.AutomationRuleResponse automationRuleResponse;

    public PostOrgsOrgIdAppsAppIdEnvsEnvIdRulesResponse withAutomationRuleResponse(demo_1.test_1.models.shared.AutomationRuleResponse automationRuleResponse) {
        this.automationRuleResponse = automationRuleResponse;
        return this;
    }
    
    
    public String contentType;

    public PostOrgsOrgIdAppsAppIdEnvsEnvIdRulesResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * The input was not a valid Automation Rule.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.ErrorInfoResponse errorInfoResponse;

    public PostOrgsOrgIdAppsAppIdEnvsEnvIdRulesResponse withErrorInfoResponse(demo_1.test_1.models.shared.ErrorInfoResponse errorInfoResponse) {
        this.errorInfoResponse = errorInfoResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public PostOrgsOrgIdAppsAppIdEnvsEnvIdRulesResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public PostOrgsOrgIdAppsAppIdEnvsEnvIdRulesResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public PostOrgsOrgIdAppsAppIdEnvsEnvIdRulesResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
