/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class PostOrgsOrgIdAppsAppIdEnvsRequest {
    /**
     * The ID, Name, Type, and Deployment the Environment will be derived from.
     * 
     * 
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    public demo_1.test_1.models.shared.EnvironmentDefinitionRequest environmentDefinitionRequest;
    public PostOrgsOrgIdAppsAppIdEnvsRequest withEnvironmentDefinitionRequest(demo_1.test_1.models.shared.EnvironmentDefinitionRequest environmentDefinitionRequest) {
        this.environmentDefinitionRequest = environmentDefinitionRequest;
        return this;
    }
    
    /**
     * The Application ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=appId")
    public String appId;
    public PostOrgsOrgIdAppsAppIdEnvsRequest withAppId(String appId) {
        this.appId = appId;
        return this;
    }
    
    /**
     * The Organization ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;
    public PostOrgsOrgIdAppsAppIdEnvsRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    public PostOrgsOrgIdAppsAppIdEnvsRequest(@JsonProperty("EnvironmentDefinitionRequest") demo_1.test_1.models.shared.EnvironmentDefinitionRequest environmentDefinitionRequest, @JsonProperty("appId") String appId, @JsonProperty("orgId") String orgId) {
        this.environmentDefinitionRequest = environmentDefinitionRequest;
        this.appId = appId;
        this.orgId = orgId;
  }
}
