/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class PostOrgsOrgIdInvitationsRequest {
    /**
     * The email and the desired role
     * 
     * 
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    public demo_1.test_1.models.shared.UserInviteRequestRequest userInviteRequestRequest;
    public PostOrgsOrgIdInvitationsRequest withUserInviteRequestRequest(demo_1.test_1.models.shared.UserInviteRequestRequest userInviteRequestRequest) {
        this.userInviteRequestRequest = userInviteRequestRequest;
        return this;
    }
    
    /**
     * The Organization ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;
    public PostOrgsOrgIdInvitationsRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    public PostOrgsOrgIdInvitationsRequest(@JsonProperty("UserInviteRequestRequest") demo_1.test_1.models.shared.UserInviteRequestRequest userInviteRequestRequest, @JsonProperty("orgId") String orgId) {
        this.userInviteRequestRequest = userInviteRequestRequest;
        this.orgId = orgId;
  }
}
