/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class PostOrgsOrgIdAppsAppIdValueSetVersionsValueSetVersionIdRestoreRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public demo_1.test_1.models.shared.ValueSetActionPayloadRequest valueSetActionPayloadRequest;
    public PostOrgsOrgIdAppsAppIdValueSetVersionsValueSetVersionIdRestoreRequest withValueSetActionPayloadRequest(demo_1.test_1.models.shared.ValueSetActionPayloadRequest valueSetActionPayloadRequest) {
        this.valueSetActionPayloadRequest = valueSetActionPayloadRequest;
        return this;
    }
    
    /**
     * The Application ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=appId")
    public String appId;
    public PostOrgsOrgIdAppsAppIdValueSetVersionsValueSetVersionIdRestoreRequest withAppId(String appId) {
        this.appId = appId;
        return this;
    }
    
    /**
     * The Organization ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;
    public PostOrgsOrgIdAppsAppIdValueSetVersionsValueSetVersionIdRestoreRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    /**
     * The ValueSetVersion ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=valueSetVersionId")
    public String valueSetVersionId;
    public PostOrgsOrgIdAppsAppIdValueSetVersionsValueSetVersionIdRestoreRequest withValueSetVersionId(String valueSetVersionId) {
        this.valueSetVersionId = valueSetVersionId;
        return this;
    }
    
    public PostOrgsOrgIdAppsAppIdValueSetVersionsValueSetVersionIdRestoreRequest(@JsonProperty("ValueSetActionPayloadRequest") demo_1.test_1.models.shared.ValueSetActionPayloadRequest valueSetActionPayloadRequest, @JsonProperty("appId") String appId, @JsonProperty("orgId") String orgId, @JsonProperty("valueSetVersionId") String valueSetVersionId) {
        this.valueSetActionPayloadRequest = valueSetActionPayloadRequest;
        this.appId = appId;
        this.orgId = orgId;
        this.valueSetVersionId = valueSetVersionId;
  }
}
