/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class PostOrgsOrgIdWorkloadProfilesProfileQidVersionsRequest {
    /**
     * Workload profile version metadata.
     * 
     * 
     */
    @SpeakeasyMetadata("request:mediaType=multipart/form-data")
    public PostOrgsOrgIdWorkloadProfilesProfileQidVersionsRequestBody requestBody;
    public PostOrgsOrgIdWorkloadProfilesProfileQidVersionsRequest withRequestBody(PostOrgsOrgIdWorkloadProfilesProfileQidVersionsRequestBody requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * The Organization ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;
    public PostOrgsOrgIdWorkloadProfilesProfileQidVersionsRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    /**
     * The Workload Profile ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=profileQid")
    public String profileQid;
    public PostOrgsOrgIdWorkloadProfilesProfileQidVersionsRequest withProfileQid(String profileQid) {
        this.profileQid = profileQid;
        return this;
    }
    
    public PostOrgsOrgIdWorkloadProfilesProfileQidVersionsRequest(@JsonProperty("RequestBody") PostOrgsOrgIdWorkloadProfilesProfileQidVersionsRequestBody requestBody, @JsonProperty("orgId") String orgId, @JsonProperty("profileQid") String profileQid) {
        this.requestBody = requestBody;
        this.orgId = orgId;
        this.profileQid = profileQid;
  }
}
