/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class PostOrgsOrgIdAppsAppIdDeltasRequest {
    /**
     * A Deployment Delta to create.
     * 
     * The Deployment Delta will be added with the provided content of `modules` and the 'env_id' and 'name' properties of the 'metadata' property.
     * 
     * NOTE: If the `id` property is specified, it will be ignored. A new ID will be generated and returned in the response.
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    public demo_1.test_1.models.shared.DeltaRequest deltaRequest;
    public PostOrgsOrgIdAppsAppIdDeltasRequest withDeltaRequest(demo_1.test_1.models.shared.DeltaRequest deltaRequest) {
        this.deltaRequest = deltaRequest;
        return this;
    }
    
    /**
     * The Application ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=appId")
    public String appId;
    public PostOrgsOrgIdAppsAppIdDeltasRequest withAppId(String appId) {
        this.appId = appId;
        return this;
    }
    
    /**
     * The Organization ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;
    public PostOrgsOrgIdAppsAppIdDeltasRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    public PostOrgsOrgIdAppsAppIdDeltasRequest(@JsonProperty("DeltaRequest") demo_1.test_1.models.shared.DeltaRequest deltaRequest, @JsonProperty("appId") String appId, @JsonProperty("orgId") String orgId) {
        this.deltaRequest = deltaRequest;
        this.appId = appId;
        this.orgId = orgId;
  }
}
