/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class PostOrgsOrgIdAppsAppIdEnvsEnvIdValuesResponse {
    
    public String contentType;

    public PostOrgsOrgIdAppsAppIdEnvsEnvIdValuesResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Input not valid.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse;

    public PostOrgsOrgIdAppsAppIdEnvsEnvIdValuesResponse withHumanitecErrorResponse(demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse) {
        this.humanitecErrorResponse = humanitecErrorResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public PostOrgsOrgIdAppsAppIdEnvsEnvIdValuesResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public PostOrgsOrgIdAppsAppIdEnvsEnvIdValuesResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Shared Value successfully created.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.ValueResponse valueResponse;

    public PostOrgsOrgIdAppsAppIdEnvsEnvIdValuesResponse withValueResponse(demo_1.test_1.models.shared.ValueResponse valueResponse) {
        this.valueResponse = valueResponse;
        return this;
    }
    
    public PostOrgsOrgIdAppsAppIdEnvsEnvIdValuesResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
