/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class PostOrgsOrgIdResourcesDefsResponse {
    
    public String contentType;
    public PostOrgsOrgIdResourcesDefsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * One or more request parameters is missing or invalid.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse;
    public PostOrgsOrgIdResourcesDefsResponse withHumanitecErrorResponse(demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse) {
        this.humanitecErrorResponse = humanitecErrorResponse;
        return this;
    }
    
    /**
     * The newly created Resources Definition details.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.ResourceDefinitionResponse resourceDefinitionResponse;
    public PostOrgsOrgIdResourcesDefsResponse withResourceDefinitionResponse(demo_1.test_1.models.shared.ResourceDefinitionResponse resourceDefinitionResponse) {
        this.resourceDefinitionResponse = resourceDefinitionResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public PostOrgsOrgIdResourcesDefsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public PostOrgsOrgIdResourcesDefsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public PostOrgsOrgIdResourcesDefsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
