/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class PostOrgsOrgIdAppsAppIdEnvsEnvIdValueSetVersionsValueSetVersionIdPurgeKeyRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public demo_1.test_1.models.shared.ValueSetActionPayloadRequest valueSetActionPayloadRequest;

    public PostOrgsOrgIdAppsAppIdEnvsEnvIdValueSetVersionsValueSetVersionIdPurgeKeyRequest withValueSetActionPayloadRequest(demo_1.test_1.models.shared.ValueSetActionPayloadRequest valueSetActionPayloadRequest) {
        this.valueSetActionPayloadRequest = valueSetActionPayloadRequest;
        return this;
    }
    
    /**
     * The Application ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=appId")
    public String appId;

    public PostOrgsOrgIdAppsAppIdEnvsEnvIdValueSetVersionsValueSetVersionIdPurgeKeyRequest withAppId(String appId) {
        this.appId = appId;
        return this;
    }
    
    /**
     * The Environment ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=envId")
    public String envId;

    public PostOrgsOrgIdAppsAppIdEnvsEnvIdValueSetVersionsValueSetVersionIdPurgeKeyRequest withEnvId(String envId) {
        this.envId = envId;
        return this;
    }
    
    /**
     * Key of the value to be purged.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=key")
    public String key;

    public PostOrgsOrgIdAppsAppIdEnvsEnvIdValueSetVersionsValueSetVersionIdPurgeKeyRequest withKey(String key) {
        this.key = key;
        return this;
    }
    
    /**
     * The Organization ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;

    public PostOrgsOrgIdAppsAppIdEnvsEnvIdValueSetVersionsValueSetVersionIdPurgeKeyRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    /**
     * The ValueSetVersion ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=valueSetVersionId")
    public String valueSetVersionId;

    public PostOrgsOrgIdAppsAppIdEnvsEnvIdValueSetVersionsValueSetVersionIdPurgeKeyRequest withValueSetVersionId(String valueSetVersionId) {
        this.valueSetVersionId = valueSetVersionId;
        return this;
    }
    
    public PostOrgsOrgIdAppsAppIdEnvsEnvIdValueSetVersionsValueSetVersionIdPurgeKeyRequest(@JsonProperty("ValueSetActionPayloadRequest") demo_1.test_1.models.shared.ValueSetActionPayloadRequest valueSetActionPayloadRequest, @JsonProperty("appId") String appId, @JsonProperty("envId") String envId, @JsonProperty("key") String key, @JsonProperty("orgId") String orgId, @JsonProperty("valueSetVersionId") String valueSetVersionId) {
        this.valueSetActionPayloadRequest = valueSetActionPayloadRequest;
        this.appId = appId;
        this.envId = envId;
        this.key = key;
        this.orgId = orgId;
        this.valueSetVersionId = valueSetVersionId;
  }
}
