/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class PutOrgsOrgIdResourcesDriversDriverIdRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public demo_1.test_1.models.shared.UpdateDriverRequestRequest updateDriverRequestRequest;
    public PutOrgsOrgIdResourcesDriversDriverIdRequest withUpdateDriverRequestRequest(demo_1.test_1.models.shared.UpdateDriverRequestRequest updateDriverRequestRequest) {
        this.updateDriverRequestRequest = updateDriverRequestRequest;
        return this;
    }
    
    /**
     * The Resource Driver ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=driverId")
    public String driverId;
    public PutOrgsOrgIdResourcesDriversDriverIdRequest withDriverId(String driverId) {
        this.driverId = driverId;
        return this;
    }
    
    /**
     * The Organization ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;
    public PutOrgsOrgIdResourcesDriversDriverIdRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    public PutOrgsOrgIdResourcesDriversDriverIdRequest(@JsonProperty("UpdateDriverRequestRequest") demo_1.test_1.models.shared.UpdateDriverRequestRequest updateDriverRequestRequest, @JsonProperty("driverId") String driverId, @JsonProperty("orgId") String orgId) {
        this.updateDriverRequestRequest = updateDriverRequestRequest;
        this.driverId = driverId;
        this.orgId = orgId;
  }
}
