/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class PutOrgsOrgIdAppsAppIdEnvsEnvIdRulesRuleIdResponse {
    /**
     * The AutomationRule
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.AutomationRuleResponse automationRuleResponse;
    public PutOrgsOrgIdAppsAppIdEnvsEnvIdRulesRuleIdResponse withAutomationRuleResponse(demo_1.test_1.models.shared.AutomationRuleResponse automationRuleResponse) {
        this.automationRuleResponse = automationRuleResponse;
        return this;
    }
    
    
    public String contentType;
    public PutOrgsOrgIdAppsAppIdEnvsEnvIdRulesRuleIdResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * The input was not a valid Automation Rule.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.ErrorInfoResponse errorInfoResponse;
    public PutOrgsOrgIdAppsAppIdEnvsEnvIdRulesRuleIdResponse withErrorInfoResponse(demo_1.test_1.models.shared.ErrorInfoResponse errorInfoResponse) {
        this.errorInfoResponse = errorInfoResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public PutOrgsOrgIdAppsAppIdEnvsEnvIdRulesRuleIdResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public PutOrgsOrgIdAppsAppIdEnvsEnvIdRulesRuleIdResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public PutOrgsOrgIdAppsAppIdEnvsEnvIdRulesRuleIdResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
