/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import demo_1.test_1.utils.SpeakeasyMetadata;

public class PutOrgsOrgIdAppsAppIdDeltasDeltaIdMetadataEnvIdRequest {
    /**
     * The new Environment ID. (NOTE: The string must still be JSON encoded.)
     * 
     * 
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    public String requestBody;
    public PutOrgsOrgIdAppsAppIdDeltasDeltaIdMetadataEnvIdRequest withRequestBody(String requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * The Application ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=appId")
    public String appId;
    public PutOrgsOrgIdAppsAppIdDeltasDeltaIdMetadataEnvIdRequest withAppId(String appId) {
        this.appId = appId;
        return this;
    }
    
    /**
     * ID of the Deployment Delta.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=deltaId")
    public String deltaId;
    public PutOrgsOrgIdAppsAppIdDeltasDeltaIdMetadataEnvIdRequest withDeltaId(String deltaId) {
        this.deltaId = deltaId;
        return this;
    }
    
    /**
     * The Organization ID.
     * 
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    public String orgId;
    public PutOrgsOrgIdAppsAppIdDeltasDeltaIdMetadataEnvIdRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    public PutOrgsOrgIdAppsAppIdDeltasDeltaIdMetadataEnvIdRequest(@JsonProperty("RequestBody") String requestBody, @JsonProperty("appId") String appId, @JsonProperty("deltaId") String deltaId, @JsonProperty("orgId") String orgId) {
        this.requestBody = requestBody;
        this.appId = appId;
        this.deltaId = deltaId;
        this.orgId = orgId;
  }
}
