/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class PutOrgsOrgIdAppsAppIdDeltasDeltaIdMetadataEnvIdResponse {
    
    public String contentType;
    public PutOrgsOrgIdAppsAppIdDeltasDeltaIdMetadataEnvIdResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * The request was invalid.
     * 
     * 
     */
    
    public demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse;
    public PutOrgsOrgIdAppsAppIdDeltasDeltaIdMetadataEnvIdResponse withHumanitecErrorResponse(demo_1.test_1.models.shared.HumanitecErrorResponse humanitecErrorResponse) {
        this.humanitecErrorResponse = humanitecErrorResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public PutOrgsOrgIdAppsAppIdDeltasDeltaIdMetadataEnvIdResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public PutOrgsOrgIdAppsAppIdDeltasDeltaIdMetadataEnvIdResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * No Deployment Delta with ID `deltaId` found in Application.
     * 
     * 
     */
    
    public String putOrgsOrgIdAppsAppIdDeltasDeltaIdMetadataEnvId404ApplicationJSONString;
    public PutOrgsOrgIdAppsAppIdDeltasDeltaIdMetadataEnvIdResponse withPutOrgsOrgIdAppsAppIdDeltasDeltaIdMetadataEnvId404ApplicationJSONString(String putOrgsOrgIdAppsAppIdDeltasDeltaIdMetadataEnvId404ApplicationJSONString) {
        this.putOrgsOrgIdAppsAppIdDeltasDeltaIdMetadataEnvId404ApplicationJSONString = putOrgsOrgIdAppsAppIdDeltasDeltaIdMetadataEnvId404ApplicationJSONString;
        return this;
    }
    
    public PutOrgsOrgIdAppsAppIdDeltasDeltaIdMetadataEnvIdResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
