/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ArtefactResponse - Artefacts can be registered with Humanitec. Continuous Integration (CI) pipelines notify Humanitec when a new version of an Artefact becomes available. Humanitec tracks the Artefact along with metadata about how it was built.
 */
public class ArtefactResponse {
    /**
     * The time when the Artefact was added to Humanitec.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("created_at")
    public String createdAt;
    public ArtefactResponse withCreatedAt(String createdAt) {
        this.createdAt = createdAt;
        return this;
    }
    
    /**
     * The user ID of the user who added the Artefact to Humanitec.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("created_by")
    public String createdBy;
    public ArtefactResponse withCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }
    
    /**
     * The UUID of the Artefact.
     */
    @JsonProperty("id")
    public String id;
    public ArtefactResponse withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * The name of the Artefact.
     */
    @JsonProperty("name")
    public String name;
    public ArtefactResponse withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * The type of the Artefact.
     */
    @JsonProperty("type")
    public String type;
    public ArtefactResponse withType(String type) {
        this.type = type;
        return this;
    }
    
    /**
     * The time when the Artefact was updated for the last time.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("updated_at")
    public String updatedAt;
    public ArtefactResponse withUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }
    
    /**
     * The user ID of the user who updated the Artefact for the last time.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("updated_by")
    public String updatedBy;
    public ArtefactResponse withUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }
    
    public ArtefactResponse(@JsonProperty("id") String id, @JsonProperty("name") String name, @JsonProperty("type") String type) {
        this.id = id;
        this.name = name;
        this.type = type;
  }
}
