/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ControllerRequest - Controller represents deployment, stateful set etc
 */
public class ControllerRequest {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("kind")
    public String kind;
    public ControllerRequest withKind(String kind) {
        this.kind = kind;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("message")
    public String message;
    public ControllerRequest withMessage(String message) {
        this.message = message;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("pods")
    public PodStateRequest[] pods;
    public ControllerRequest withPods(PodStateRequest[] pods) {
        this.pods = pods;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("replicas")
    public Long replicas;
    public ControllerRequest withReplicas(Long replicas) {
        this.replicas = replicas;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("revision")
    public Long revision;
    public ControllerRequest withRevision(Long revision) {
        this.revision = revision;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    public String status;
    public ControllerRequest withStatus(String status) {
        this.status = status;
        return this;
    }
    
    public ControllerRequest(){}
}
