/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ControllerResponse - Controller represents deployment, stateful set etc
 */
public class ControllerResponse {
    @JsonProperty("kind")
    public String kind;
    public ControllerResponse withKind(String kind) {
        this.kind = kind;
        return this;
    }
    
    @JsonProperty("message")
    public String message;
    public ControllerResponse withMessage(String message) {
        this.message = message;
        return this;
    }
    
    @JsonProperty("pods")
    public PodStateResponse[] pods;
    public ControllerResponse withPods(PodStateResponse[] pods) {
        this.pods = pods;
        return this;
    }
    
    @JsonProperty("replicas")
    public Long replicas;
    public ControllerResponse withReplicas(Long replicas) {
        this.replicas = replicas;
        return this;
    }
    
    @JsonProperty("revision")
    public Long revision;
    public ControllerResponse withRevision(Long revision) {
        this.revision = revision;
        return this;
    }
    
    @JsonProperty("status")
    public String status;
    public ControllerResponse withStatus(String status) {
        this.status = status;
        return this;
    }
    
    public ControllerResponse(@JsonProperty("kind") String kind, @JsonProperty("message") String message, @JsonProperty("pods") PodStateResponse[] pods, @JsonProperty("replicas") Long replicas, @JsonProperty("revision") Long revision, @JsonProperty("status") String status) {
        this.kind = kind;
        this.message = message;
        this.pods = pods;
        this.replicas = replicas;
        this.revision = revision;
        this.status = status;
  }
}
