/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateResourceAccountRequestRequest - CreateResourceAccountRequest describes the request to create a new security account.
 */
public class CreateResourceAccountRequestRequest {
    /**
     * Credentials associated with the account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("credentials")
    public java.util.Map<String, Object> credentials;

    public CreateResourceAccountRequestRequest withCredentials(java.util.Map<String, Object> credentials) {
        this.credentials = credentials;
        return this;
    }
    
    /**
     * Unique identifier for the account (in scope of the organization it belongs to).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    public String id;

    public CreateResourceAccountRequestRequest withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * Display name.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;

    public CreateResourceAccountRequestRequest withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * The type of the account
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    public String type;

    public CreateResourceAccountRequestRequest withType(String type) {
        this.type = type;
        return this;
    }
    
    public CreateResourceAccountRequestRequest(){}
}
