/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * DeltaRequest - A Deployment Delta (or just "Delta") describes the changes that must be applied to one Deployment Set to generate another Deployment Set. Deployment Deltas are the only way to create new Deployment Sets.
 * 
 * Deployment Deltas can be created fully formed or combined together via PATCHing. They can also be generated from the difference between two Deployment Sets.
 * 
 * **Basic Structure**
 * 
 * ```
 *  {
 *    "id": &lt;ID of the Deployment Delta.&gt;,
 *    "metadata": {
 *      &lt;Properties such as who created the Delta, which Environment it is associated to and a Human-friendly name&gt;
 *    }
 *    "modules" : {
 *      "add" : {
 *        &lt;ID of Module to add to the Deployment Set&gt; : {
 *          &lt;An entire Modules object&gt;
 *        }
 *      },
 *      "remove": [
 *        &lt;An array of Module IDs that should be removed from the Deployment Set&gt;
 *      ],
 *     "update": {
 *        &lt;ID of Module already in the Set to be updated&gt; : [
 *          &lt;An array of JSON Patch (Search Results (RFC 6902) objects scoped to the module&gt;
 *        ]
 *      }
 *    }
 *  }
 * ```
 */
public class DeltaRequest {
    /**
     * Ignored, but can be provided.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    public String id;

    public DeltaRequest withId(String id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("metadata")
    public DeltaMetadataRequest metadata;

    public DeltaRequest withMetadata(DeltaMetadataRequest metadata) {
        this.metadata = metadata;
        return this;
    }
    
    /**
     * ModuleDeltas groups the different operations together.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("modules")
    public ModuleDeltasRequest modules;

    public DeltaRequest withModules(ModuleDeltasRequest modules) {
        this.modules = modules;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("shared")
    public UpdateActionRequest[] shared;

    public DeltaRequest withShared(UpdateActionRequest[] shared) {
        this.shared = shared;
        return this;
    }
    
    public DeltaRequest(){}
}
