/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import demo_1.test_1.utils.DateTimeDeserializer;
import demo_1.test_1.utils.DateTimeSerializer;
import java.time.OffsetDateTime;

public class DeltaMetadataResponse {
    @JsonProperty("archived")
    public Boolean archived;
    public DeltaMetadataResponse withArchived(Boolean archived) {
        this.archived = archived;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("contributers")
    public String[] contributers;
    public DeltaMetadataResponse withContributers(String[] contributers) {
        this.contributers = contributers;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created_at")
    public OffsetDateTime createdAt;
    public DeltaMetadataResponse withCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }
    
    @JsonProperty("created_by")
    public String createdBy;
    public DeltaMetadataResponse withCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("env_id")
    public String envId;
    public DeltaMetadataResponse withEnvId(String envId) {
        this.envId = envId;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("last_modified_at")
    public OffsetDateTime lastModifiedAt;
    public DeltaMetadataResponse withLastModifiedAt(OffsetDateTime lastModifiedAt) {
        this.lastModifiedAt = lastModifiedAt;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;
    public DeltaMetadataResponse withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("shared")
    public Boolean shared;
    public DeltaMetadataResponse withShared(Boolean shared) {
        this.shared = shared;
        return this;
    }
    
    public DeltaMetadataResponse(@JsonProperty("archived") Boolean archived, @JsonProperty("created_at") OffsetDateTime createdAt, @JsonProperty("created_by") String createdBy, @JsonProperty("last_modified_at") OffsetDateTime lastModifiedAt) {
        this.archived = archived;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
        this.lastModifiedAt = lastModifiedAt;
  }
}
