/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * DeploymentErrorResponse - DeploymentError is an error happening during deployment
 */
public class DeploymentErrorResponse {
    @JsonProperty("code")
    public String code;

    public DeploymentErrorResponse withCode(String code) {
        this.code = code;
        return this;
    }
    
    @JsonProperty("error_type")
    public String errorType;

    public DeploymentErrorResponse withErrorType(String errorType) {
        this.errorType = errorType;
        return this;
    }
    
    @JsonProperty("message")
    public String message;

    public DeploymentErrorResponse withMessage(String message) {
        this.message = message;
        return this;
    }
    
    @JsonProperty("object_id")
    public String objectId;

    public DeploymentErrorResponse withObjectId(String objectId) {
        this.objectId = objectId;
        return this;
    }
    
    @JsonProperty("scope")
    public String scope;

    public DeploymentErrorResponse withScope(String scope) {
        this.scope = scope;
        return this;
    }
    
    @JsonProperty("summary")
    public String summary;

    public DeploymentErrorResponse withSummary(String summary) {
        this.summary = summary;
        return this;
    }
    
    public DeploymentErrorResponse(@JsonProperty("code") String code, @JsonProperty("error_type") String errorType, @JsonProperty("message") String message, @JsonProperty("object_id") String objectId, @JsonProperty("scope") String scope, @JsonProperty("summary") String summary) {
        this.code = code;
        this.errorType = errorType;
        this.message = message;
        this.objectId = objectId;
        this.scope = scope;
        this.summary = summary;
  }
}
