/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * EnvironmentTypeRequest - Environment Types are a way of grouping and managing Environments. Every Environment has exactly 1 Environment Type.
 * 
 * Environment Types can be used with External Resources to manage where resources such as databases are provisioned or even which cluster to deploy to.
 */
public class EnvironmentTypeRequest {
    /**
     * A Human-readable description of the Environment Type
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    public String description;

    public EnvironmentTypeRequest withDescription(String description) {
        this.description = description;
        return this;
    }
    
    /**
     * The ID of the Environment Type. (Must be unique within an Organization.)
     */
    @JsonProperty("id")
    public String id;

    public EnvironmentTypeRequest withId(String id) {
        this.id = id;
        return this;
    }
    
    public EnvironmentTypeRequest(@JsonProperty("id") String id) {
        this.id = id;
  }
}
