/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * EnvironmentRuntimeInfoResponse - EnvironmentRuntimeInfo
 */
public class EnvironmentRuntimeInfoResponse {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("error")
    public String error;
    public EnvironmentRuntimeInfoResponse withError(String error) {
        this.error = error;
        return this;
    }
    
    @JsonProperty("id")
    public String id;
    public EnvironmentRuntimeInfoResponse withId(String id) {
        this.id = id;
        return this;
    }
    
    @JsonProperty("paused")
    public Boolean paused;
    public EnvironmentRuntimeInfoResponse withPaused(Boolean paused) {
        this.paused = paused;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    public String status;
    public EnvironmentRuntimeInfoResponse withStatus(String status) {
        this.status = status;
        return this;
    }
    
    public EnvironmentRuntimeInfoResponse(@JsonProperty("id") String id, @JsonProperty("paused") Boolean paused) {
        this.id = id;
        this.paused = paused;
  }
}
