/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * EventBaseResponse - Properties which identify an event .
 */
public class EventBaseResponse {
    /**
     * Event scope
     */
    @JsonProperty("scope")
    public String scope;
    public EventBaseResponse withScope(String scope) {
        this.scope = scope;
        return this;
    }
    
    /**
     * Event type
     */
    @JsonProperty("type")
    public String type;
    public EventBaseResponse withType(String type) {
        this.type = type;
        return this;
    }
    
    public EventBaseResponse(@JsonProperty("scope") String scope, @JsonProperty("type") String type) {
        this.scope = scope;
        this.type = type;
  }
}
