/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * EventResponse - Events available for triggering automated jobs.
 */
public class EventResponse {
    /**
     * List of event properties which can be used as variables for this event
     */
    @JsonProperty("properties")
    public String[] properties;
    public EventResponse withProperties(String[] properties) {
        this.properties = properties;
        return this;
    }
    
    /**
     * Event scope
     */
    @JsonProperty("scope")
    public String scope;
    public EventResponse withScope(String scope) {
        this.scope = scope;
        return this;
    }
    
    /**
     * Event type
     */
    @JsonProperty("type")
    public String type;
    public EventResponse withType(String type) {
        this.type = type;
        return this;
    }
    
    public EventResponse(@JsonProperty("properties") String[] properties, @JsonProperty("scope") String scope, @JsonProperty("type") String type) {
        this.properties = properties;
        this.scope = scope;
        this.type = type;
  }
}
