/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PatchResourceDefinitionRequestRequest - PatchResourceDefinitionRequest describes a ResourceDefinition change request.
 */
public class PatchResourceDefinitionRequestRequest {
    /**
     * (Optional) Security account required by the driver.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("driver_account")
    public String driverAccount;
    public PatchResourceDefinitionRequestRequest withDriverAccount(String driverAccount) {
        this.driverAccount = driverAccount;
        return this;
    }
    
    /**
     * ValuesSecrets stores data that should be passed around split by sensitivity.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("driver_inputs")
    public ValuesSecretsRequest driverInputs;
    public PatchResourceDefinitionRequestRequest withDriverInputs(ValuesSecretsRequest driverInputs) {
        this.driverInputs = driverInputs;
        return this;
    }
    
    /**
     * (Optional) Resource display name
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;
    public PatchResourceDefinitionRequestRequest withName(String name) {
        this.name = name;
        return this;
    }
    
    public PatchResourceDefinitionRequestRequest(){}
}
