/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PodStateRequest - PodState represents single pod status
 */
public class PodStateRequest {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("containerStatuses")
    public java.util.Map<String, Object>[] containerStatuses;

    public PodStateRequest withContainerStatuses(java.util.Map<String, Object>[] containerStatuses) {
        this.containerStatuses = containerStatuses;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("phase")
    public String phase;

    public PodStateRequest withPhase(String phase) {
        this.phase = phase;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("podName")
    public String podName;

    public PodStateRequest withPodName(String podName) {
        this.podName = podName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("revision")
    public Long revision;

    public PodStateRequest withRevision(Long revision) {
        this.revision = revision;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    public String status;

    public PodStateRequest withStatus(String status) {
        this.status = status;
        return this;
    }
    
    public PodStateRequest(){}
}
