/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * RegistryCredsResponse - RegistryCreds represents current registry credentials (either, username- or token-based).
 */
public class RegistryCredsResponse {
    /**
     * Account credentials expiration timestamp.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("expires")
    public String expires;

    public RegistryCredsResponse withExpires(String expires) {
        this.expires = expires;
        return this;
    }
    
    /**
     * Account password or token secret.
     */
    @JsonProperty("password")
    public String password;

    public RegistryCredsResponse withPassword(String password) {
        this.password = password;
        return this;
    }
    
    /**
     * Registry name, usually in a "{domain}" or "{domain}/{project}" format.
     */
    @JsonProperty("registry")
    public String registry;

    public RegistryCredsResponse withRegistry(String registry) {
        this.registry = registry;
        return this;
    }
    
    /**
     * ClusterSecretsMap stores a list of Kuberenetes secret references for the target deployment clusters.
     */
    @JsonProperty("secrets")
    public java.util.Map<String, ClusterSecretResponse> secrets;

    public RegistryCredsResponse withSecrets(java.util.Map<String, ClusterSecretResponse> secrets) {
        this.secrets = secrets;
        return this;
    }
    
    /**
     * Security account login or token.
     */
    @JsonProperty("username")
    public String username;

    public RegistryCredsResponse withUsername(String username) {
        this.username = username;
        return this;
    }
    
    public RegistryCredsResponse(@JsonProperty("username") String username, @JsonProperty("password") String password, @JsonProperty("registry") String registry, @JsonProperty("secrets") java.util.Map<String, ClusterSecretResponse> secrets) {
        this.username = username;
        this.password = password;
        this.registry = registry;
        this.secrets = secrets;
  }
}
