/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * RegistryRequest - Humanitec can be used to manage registry credentials. The Registry object represents how to match credentials to a particular registry.
 * 
 * Humanitec supports all Docker compatible registries as well as the custom authentication formats used by AWS Elastic Container Registry and Google Container Registry. It also supports the injection of a specific secret to be copied from an existing namespace in the cluster.
 */
public class RegistryRequest {
    /**
     * AccountCreds represents an account credentials (either, username- or token-based).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("creds")
    public AccountCredsRequest creds;
    public RegistryRequest withCreds(AccountCredsRequest creds) {
        this.creds = creds;
        return this;
    }
    
    /**
     * Indicates if registry secrets and credentials should be exposed to CI agents.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("enable_ci")
    public Boolean enableCi;
    public RegistryRequest withEnableCi(Boolean enableCi) {
        this.enableCi = enableCi;
        return this;
    }
    
    /**
     * Registry ID, unique within the Organization.
     */
    @JsonProperty("id")
    public String id;
    public RegistryRequest withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * Registry name, usually in a "{domain}" or "{domain}/{project}" format.
     */
    @JsonProperty("registry")
    public String registry;
    public RegistryRequest withRegistry(String registry) {
        this.registry = registry;
        return this;
    }
    
    /**
     * ClusterSecretsMap stores a list of Kuberenetes secret references for the target deployment clusters.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("secrets")
    public java.util.Map<String, ClusterSecretRequest> secrets;
    public RegistryRequest withSecrets(java.util.Map<String, ClusterSecretRequest> secrets) {
        this.secrets = secrets;
        return this;
    }
    
    /**
     * Registry type, describes the registry authentication method, and defines the schema for the credentials.
     * 
     * Supported values:
     * 
     * - `public`
     * 
     * - `basic`
     * 
     * - `google_gcr`
     * 
     * - `amazon_ecr`
     * 
     * - `secret_ref`
     */
    @JsonProperty("type")
    public String type;
    public RegistryRequest withType(String type) {
        this.type = type;
        return this;
    }
    
    public RegistryRequest(@JsonProperty("id") String id, @JsonProperty("registry") String registry, @JsonProperty("type") String type) {
        this.id = id;
        this.registry = registry;
        this.type = type;
  }
}
