/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * RegistryResponse - Humanitec can be used to manage registry credentials. The Registry object represents how to match credentials to a particular registry.
 * 
 * Humanitec supports all Docker compatible registries as well as the custom authentication formats used by AWS Elastic Container Registry and Google Container Registry. It also supports the injection of a specific secret to be copied from an existing namespace in the cluster.
 */
public class RegistryResponse {
    /**
     * The timestamp of when this record was created.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("created_at")
    public String createdAt;
    public RegistryResponse withCreatedAt(String createdAt) {
        this.createdAt = createdAt;
        return this;
    }
    
    /**
     * The user who created this record.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("created_by")
    public String createdBy;
    public RegistryResponse withCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }
    
    /**
     * Indicates if registry secrets and credentials should be exposed to CI agents.
     */
    @JsonProperty("enable_ci")
    public Boolean enableCi;
    public RegistryResponse withEnableCi(Boolean enableCi) {
        this.enableCi = enableCi;
        return this;
    }
    
    /**
     * Registry ID, unique within the Organization.
     */
    @JsonProperty("id")
    public String id;
    public RegistryResponse withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * Registry name, usually in a "{domain}" or "{domain}/{project}" format.
     */
    @JsonProperty("registry")
    public String registry;
    public RegistryResponse withRegistry(String registry) {
        this.registry = registry;
        return this;
    }
    
    /**
     * ClusterSecretsMap stores a list of Kuberenetes secret references for the target deployment clusters.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("secrets")
    public java.util.Map<String, ClusterSecretResponse> secrets;
    public RegistryResponse withSecrets(java.util.Map<String, ClusterSecretResponse> secrets) {
        this.secrets = secrets;
        return this;
    }
    
    /**
     * Registry type, describes the registry authentication method, and defines the schema for the credentials.
     * 
     * Supported values:
     * 
     * - `public`
     * 
     * - `basic`
     * 
     * - `google_gcr`
     * 
     * - `amazon_ecr`
     * 
     * - `secret_ref`
     */
    @JsonProperty("type")
    public String type;
    public RegistryResponse withType(String type) {
        this.type = type;
        return this;
    }
    
    public RegistryResponse(@JsonProperty("enable_ci") Boolean enableCi, @JsonProperty("id") String id, @JsonProperty("registry") String registry, @JsonProperty("type") String type) {
        this.enableCi = enableCi;
        this.id = id;
        this.registry = registry;
        this.type = type;
  }
}
