/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ResourceDefinitionChangeResponse - ResourceDefinitionChange describes the effects of a Resource Definition or Matching Criteria update/deletion.
 */
public class ResourceDefinitionChangeResponse {
    /**
     * The ID of the App the resource is associated with.
     */
    @JsonProperty("app_id")
    public String appId;

    public ResourceDefinitionChangeResponse withAppId(String appId) {
        this.appId = appId;
        return this;
    }
    
    /**
     * The ID of the Environment the resource is associated with.
     */
    @JsonProperty("env_id")
    public String envId;

    public ResourceDefinitionChangeResponse withEnvId(String envId) {
        this.envId = envId;
        return this;
    }
    
    /**
     * The Resource Definition that this resource was provisioned from.
     */
    @JsonProperty("from_def")
    public String fromDef;

    public ResourceDefinitionChangeResponse withFromDef(String fromDef) {
        this.fromDef = fromDef;
        return this;
    }
    
    /**
     * The ID of the resource
     */
    @JsonProperty("res_id")
    public String resId;

    public ResourceDefinitionChangeResponse withResId(String resId) {
        this.resId = resId;
        return this;
    }
    
    /**
     * The Resource Definition that resource *will be* provisioned from if the change is applied.
     */
    @JsonProperty("to_def")
    public String toDef;

    public ResourceDefinitionChangeResponse withToDef(String toDef) {
        this.toDef = toDef;
        return this;
    }
    
    public ResourceDefinitionChangeResponse(@JsonProperty("app_id") String appId, @JsonProperty("env_id") String envId, @JsonProperty("from_def") String fromDef, @JsonProperty("res_id") String resId, @JsonProperty("to_def") String toDef) {
        this.appId = appId;
        this.envId = envId;
        this.fromDef = fromDef;
        this.resId = resId;
        this.toDef = toDef;
  }
}
