/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ResourceDefinitionResponse - A Resource Definitions describes how and when a resource should be provisioned. It links a driver (the how) along with a Matching Criteria (the when) to a Resource Type. This allows Humanitec to invoke a particular driver for the required Resource Type in the context of a particular Application and Environment.
 * 
 * The schema for the `driver_inputs` is defined by the `input_schema` property on the DriverDefinition identified by the `driver_type` property.
 */
public class ResourceDefinitionResponse {
    /**
     * The timestamp of when this record has been created.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("created_at")
    public String createdAt;

    public ResourceDefinitionResponse withCreatedAt(String createdAt) {
        this.createdAt = createdAt;
        return this;
    }
    
    /**
     * The user who created this record.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("created_by")
    public String createdBy;

    public ResourceDefinitionResponse withCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }
    
    /**
     * (Optional) The criteria to use when looking for a Resource Definition during the deployment.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("criteria")
    public MatchingCriteriaResponse[] criteria;

    public ResourceDefinitionResponse withCriteria(MatchingCriteriaResponse[] criteria) {
        this.criteria = criteria;
        return this;
    }
    
    /**
     * (Optional) Security account required by the driver.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("driver_account")
    public String driverAccount;

    public ResourceDefinitionResponse withDriverAccount(String driverAccount) {
        this.driverAccount = driverAccount;
        return this;
    }
    
    /**
     * ValuesSecrets stores data that should be passed around split by sensitivity.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("driver_inputs")
    public ValuesSecretsResponse driverInputs;

    public ResourceDefinitionResponse withDriverInputs(ValuesSecretsResponse driverInputs) {
        this.driverInputs = driverInputs;
        return this;
    }
    
    /**
     * The driver to be used to create the resource.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("driver_type")
    public String driverType;

    public ResourceDefinitionResponse withDriverType(String driverType) {
        this.driverType = driverType;
        return this;
    }
    
    /**
     * The Resource Definition ID.
     */
    @JsonProperty("id")
    public String id;

    public ResourceDefinitionResponse withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * Indicates this definition is a built-in one (provided by Humanitec).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("is_default")
    public Boolean isDefault;

    public ResourceDefinitionResponse withIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
        return this;
    }
    
    /**
     * Indicates if this record has been marked for deletion. The Resource Definition that has been marked for deletion cannot be used to provision new resources.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("is_deleted")
    public Boolean isDeleted;

    public ResourceDefinitionResponse withIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
        return this;
    }
    
    /**
     * The display name.
     */
    @JsonProperty("name")
    public String name;

    public ResourceDefinitionResponse withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * The Organization ID.
     */
    @JsonProperty("org_id")
    public String orgId;

    public ResourceDefinitionResponse withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    /**
     * The Resource Type.
     */
    @JsonProperty("type")
    public String type;

    public ResourceDefinitionResponse withType(String type) {
        this.type = type;
        return this;
    }
    
    public ResourceDefinitionResponse(@JsonProperty("id") String id, @JsonProperty("name") String name, @JsonProperty("org_id") String orgId, @JsonProperty("type") String type) {
        this.id = id;
        this.name = name;
        this.orgId = orgId;
        this.type = type;
  }
}
