/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * RoleRequest - Role defines the role that will be used in request
 */
public class RoleRequest {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("role")
    public String role;

    public RoleRequest withRole(String role) {
        this.role = role;
        return this;
    }
    
    public RoleRequest(){}
}
