/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * RuntimeInfoResponse - RuntimeInfo object returned by the runtime endpoint. Represents a list post statuses grouped by modules and controllers (deployments and stateful sets).
 */
public class RuntimeInfoResponse {
    @JsonProperty("modules")
    public java.util.Map<String, java.util.Map<String, ControllerResponse>> modules;

    public RuntimeInfoResponse withModules(java.util.Map<String, java.util.Map<String, ControllerResponse>> modules) {
        this.modules = modules;
        return this;
    }
    
    @JsonProperty("namespace")
    public String namespace;

    public RuntimeInfoResponse withNamespace(String namespace) {
        this.namespace = namespace;
        return this;
    }
    
    public RuntimeInfoResponse(@JsonProperty("modules") java.util.Map<String, java.util.Map<String, ControllerResponse>> modules, @JsonProperty("namespace") String namespace) {
        this.modules = modules;
        this.namespace = namespace;
  }
}
