/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * UpdateResourceDefinitionRequestRequest - UpdateResourceDefinitionRequest describes a ResourceDefinition change request.
 */
public class UpdateResourceDefinitionRequestRequest {
    /**
     * (Optional) Security account required by the driver.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("driver_account")
    public String driverAccount;

    public UpdateResourceDefinitionRequestRequest withDriverAccount(String driverAccount) {
        this.driverAccount = driverAccount;
        return this;
    }
    
    /**
     * ValuesSecrets stores data that should be passed around split by sensitivity.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("driver_inputs")
    public ValuesSecretsRequest driverInputs;

    public UpdateResourceDefinitionRequestRequest withDriverInputs(ValuesSecretsRequest driverInputs) {
        this.driverInputs = driverInputs;
        return this;
    }
    
    /**
     * The display name.
     */
    @JsonProperty("name")
    public String name;

    public UpdateResourceDefinitionRequestRequest withName(String name) {
        this.name = name;
        return this;
    }
    
    public UpdateResourceDefinitionRequestRequest(@JsonProperty("name") String name) {
        this.name = name;
  }
}
