/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * UpdateActionRequest - A representation of the main object defined in JSON Patch specified in RFC 6902 from the IETF. The main differences are:
 * 
 * * Only `add`, `remove` and `replace` are supported
 * 
 * * `remove` can have have its scope of application applied in its `value`. e.g. `{"scope":"delta"}
 */
public class UpdateActionRequest {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("from")
    public String from;
    public UpdateActionRequest withFrom(String from) {
        this.from = from;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("op")
    public String op;
    public UpdateActionRequest withOp(String op) {
        this.op = op;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("path")
    public String path;
    public UpdateActionRequest withPath(String path) {
        this.path = path;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("value")
    public Object value;
    public UpdateActionRequest withValue(Object value) {
        this.value = value;
        return this;
    }
    
    public UpdateActionRequest(){}
}
