/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ValuesSecretsResponse - ValuesSecrets stores data that should be passed around split by sensitivity.
 */
public class ValuesSecretsResponse {
    /**
     * Secrets section of the data set. Sensitive information is stored in the Vault and replaced with the Vault paths when sent outside.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("secrets")
    public java.util.Map<String, Object> secrets;

    public ValuesSecretsResponse withSecrets(java.util.Map<String, Object> secrets) {
        this.secrets = secrets;
        return this;
    }
    
    /**
     * Values section of the data set. Passed around as-is.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("values")
    public java.util.Map<String, Object> values;

    public ValuesSecretsResponse withValues(java.util.Map<String, Object> values) {
        this.values = values;
        return this;
    }
    
    public ValuesSecretsResponse(){}
}
