/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ValueCreatePayloadRequest - Definition of the new Shared Value.
 * 
 * 
 */
public class ValueCreatePayloadRequest {
    @JsonProperty("description")
    public String description;

    public ValueCreatePayloadRequest withDescription(String description) {
        this.description = description;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("is_secret")
    public Boolean isSecret;

    public ValueCreatePayloadRequest withIsSecret(Boolean isSecret) {
        this.isSecret = isSecret;
        return this;
    }
    
    @JsonProperty("key")
    public String key;

    public ValueCreatePayloadRequest withKey(String key) {
        this.key = key;
        return this;
    }
    
    @JsonProperty("value")
    public String value;

    public ValueCreatePayloadRequest withValue(String value) {
        this.value = value;
        return this;
    }
    
    public ValueCreatePayloadRequest(@JsonProperty("description") String description, @JsonProperty("key") String key, @JsonProperty("value") String value) {
        this.description = description;
        this.key = key;
        this.value = value;
  }
}
