/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package demo_1.test_1.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * WorkloadProfileVersionRequest - Each Workload Profile has one or more Versions associated with it. In order to add a version, a Workload Profile must first be created.
 */
public class WorkloadProfileVersionRequest {
    /**
     * A map of Features. If referencing built in Humanitec features, the fully qualified feature name must be used: e.g. `humanitec/annotations`.
     * 
     * {
     * 
     * }
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("features")
    public java.util.Map<String, Object> features;

    public WorkloadProfileVersionRequest withFeatures(java.util.Map<String, Object> features) {
        this.features = features;
        return this;
    }
    
    /**
     * Notes
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("notes")
    public String notes;

    public WorkloadProfileVersionRequest withNotes(String notes) {
        this.notes = notes;
        return this;
    }
    
    public WorkloadProfileVersionRequest(){}
}
